- hosts: host

  vars:
    root_dir: /var/www/ansible_lessons
    nginx_dir: /etc/nginx/
    nginx_port: 2222
    service_name: "This is server {{ ansible_facts['hostname'] }}"
    deploy_date_time: >-
      {{
        ansible_date_time.weekday
        | replace('Monday', 'Пн')
        | replace('Tuesday', 'Вт')
        | replace('Wednesday', 'Ср')
        | replace('Thursday', 'Чт')
        | replace('Friday', 'Пт')
        | replace('Saturday', 'Сб')
        | replace('Sunday', 'Вс')
      }}
      {{ ansible_date_time.day }}
      {{
        ansible_date_time.month
        | replace('01', 'янв')
        | replace('02', 'фев')
        | replace('03', 'мар')
        | replace('04', 'апр')
        | replace('05', 'май')
        | replace('06', 'июн')
        | replace('07', 'июл')
        | replace('08', 'авг')
        | replace('09', 'сен')
        | replace('10', 'окт')
        | replace('11', 'ноя')
        | replace('12', 'дек')
      }}
      {{ ansible_date_time.year }}
      {{ ansible_date_time.time }}
    users:
      - jaime
      - sansa
      - robert
  
  tasks:
    - name: Generate cowsay text
      ansible.builtin.shell: cowsay -f turtle "{{ service_name }}"
      register: what_the_cowsay
      changed_when: false
      tags: index

    - name: update_cache
      ansible.builtin.apt:
        update_cache: yes
      become: yes
      tags: app

    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes
      become: yes
      tags: app


    - name: install make
      ansible.builtin.apt:
        name: make
        state: present
        update_cache: yes
      become: yes
      tags: app

    - name: install node
      ansible.builtin.apt:
        name: nodejs
        state: present
        update_cache: yes
      become: yes
      tags: app

    - name: Create first_user
      become: yes
      ansible.builtin.user:
        name: "{{ first_user }}"
        password: "{{ first_password | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes
        state: present
      tags: user
    - name: Create second_user
      become: yes
      ansible.builtin.user:
        name: "{{ second_user }}"
        password: "{{ second_password | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes
        state: present
      tags: user
    - name: Create third_user
      become: yes
      ansible.builtin.user:
        name: "{{ third_user }}"
        password: "{{ third_password | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes
        state: present
      tags: user

    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes
      tags: nginx

    - name: install nginx
      ansible.builtin.apt:
        name: cowsay
        state: latest
      become: yes
      tags: nginx

    - name: Create site directory
      ansible.builtin.file:
        path: "{{ root_dir }}"
        state: directory
        owner: root
        group: www-data
        mode: '0755'
      become: yes
      tags: site

    - name: update nginx config
      ansible.builtin.template:
        src: templates/nginx.conf.j2

        dest: "{{ nginx_dir }}/nginx.conf"
      notify:
        - restart nginx
      become: yes
      tags: site

    - name: added index page
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: "{{ root_dir }}/index.html"
      become: yes
      tags: [site, index]

    - name: Create loop_users
      become: yes
      ansible.builtin.user:
        name: "{{ item }}"
        shell: /bin/bash
        create_home: yes
        state: present
      loop: "{{ users }}"
      tags: loop_users

    - name: update git config
      ansible.builtin.template:
        src: templates/gitconfig.j2

        dest: "/home/{{ item }}/.gitconfig"
      loop: "{{ users }}"
      become: yes
      tags: loop_users

    - name: Create ssh directory
      ansible.builtin.file:
        path: "/home/{{ item }}/.ssh/"
        state: directory
        owner: "{{ item }}"
        mode: '0700'
      become: yes
      loop: "{{ users }}"
      tags: loop_users

    - name: copy ssh key
      ansible.builtin.copy:
        src: files/authorized_key.pub
        dest: "/home/{{ item }}/.ssh/authorized_keys"
        owner: "{{ item }}"
        mode: '0600'
      loop: "{{ users }}"
      tags: loop_users

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes


